---
kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master

steps:
- name: Build VueJS
  image: node
  commands:
    - cd frontend
    - npm install
    - npm run build
- name: Package static files
  image: golang
  commands:
    - cd backend
    - go get github.com/markbates/pkger/cmd/pkger
    - pkger -include /static -include /templates

- name: Buiding for Linux
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLE: 1
  commands:
    - cd backend
    - go build -v -o dist/pidnc-linux-amd64

- name: Building for ARM
  image: henne/golang-crosscompile
  environment:
    GOOS: linux
    GOARCH: arm
    GOARM: 5
    CGO_ENABLED: 1
    CC: arm-linux-gnueabihf-gcc
    CXX: arm-linux-gnueabihf-g++
  commands:
    - cd backend
    - go build -v -o dist/pidnc-linux-arm5

- name: Building for ARM64
  image: henne/golang-crosscompile
  environment:
    GOOS: linux
    GOARCH: arm64
    CGO_ENABLED: 1
    CC: aarch64-linux-gnu-gcc
    CXX: aarch64-linux-gnu-g++
  commands:
    - cd backend
    - go build -v -o dist/pidnc-linux-arm64

- name: Creating checksums
  image: golang
  commands:
    - mkdir sums
    - md5sum backend/dist/* > sums/md5sum.txt
    - sha1sum backend/dist/* > sums/sha1sum.txt
    - sha256sum backend/dist/* > sums/sha256sum.txt
    - sha512sum backend/dist/* > sums/sha512sum.txt
    - mv sums/* backend/dist/
    - rmdir sums

- name: semantic-release
  image: henne/semantic-release
  settings:
    mode: release
    git_user_name: drone
    git_user_email: drone@example.com
    git_login: henne
    git_password:
      from_secret: gitea_password
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
    GITEA_URL: https://r.dre.li

- name: Notify Telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to: 27999067
    message: >
       {{#success build.status}}
         build {{build.number}} succeeded. Good job.
         https://drone.dre.li/henne/pidnc/{{build.number}}
       {{else}}
         build {{build.number}} failed. Fix me please.
         https://drone.dre.li/henne/pidnc/{{build.number}}
       {{/success}}
  when:
    status:
    - success
    - failure
- name: Notify Pascal Telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to: 137934255
    message: >
      {{#success build.status}}
        Neuer Build: https://r.dre.li/henne/pidnc/releases/
      {{/success}}
  when:
    status:
      - success