#!/bin/bash

export GOOS=linux
export GOARCH=amd64
# export CC=x86_64-linux-musl-gcc
# export CXX=x86_64-linux-musl-g++

~/go/bin/pkger -include /static -include /templates

# go build -v -ldflags="-extldflags=-static" .
go build -v -o dist/pidnc-linux-x64 .

export GOARCH=arm
export GOARM=5

go build -v -o dist/pidnc-linux-arm-5 .
rm pkged.go
